#!/bin/bash
#check JAVA_HOME & java
noJavaHome=false
if [ -z "$JAVA_HOME" ] ; then
    noJavaHome=true
fi
if [ ! -e "$JAVA_HOME/bin/java" ] ; then
    noJavaHome=true
fi
if $noJavaHome ; then
    echo
    echo "Error: JAVA_HOME environment variable is not set."
    echo
    exit 1
fi
#==============================================================================

#set HOME
CURR_DIR=`pwd`
LPPZ_MICRO_HOME=`pwd`
cd $CURR_DIR
if [ -z "$LPPZ_MICRO_HOME" ] ; then
    echo
    echo "Error: LPPZ_MICRO_HOME environment variable is not defined correctly."
    echo
    exit 1
fi
#==============================================================================

#set CLASSPATH
LPPZ_MICRO_CLASSPATH="$LPPZ_MICRO_HOME/conf:$LPPZ_MICRO_HOME/lib/classes"
for i in "$LPPZ_MICRO_HOME"/lib/*.jar
do
    LPPZ_MICRO_CLASSPATH="$LPPZ_MICRO_CLASSPATH:$i"
done
#==============================================================================

#destory Server
RUN_CMD="\"$JAVA_HOME/bin/java\""
RUN_CMD="$RUN_CMD -DLOG_HOME=\"logbiz\""
RUN_CMD="$RUN_CMD -classpath \"$LPPZ_MICRO_CLASSPATH\""
RUN_CMD="$RUN_CMD com.lppz.mirc.redis.RedisMircServiceDestory $@"
RUN_CMD="$RUN_CMD > \"/dev/null\" 2>&1 &"
echo $RUN_CMD
eval $RUN_CMD
#==============================================================================