#!/bin/bash
targetDir="target/kernel-lppz-hive"
mvn clean dependency:copy-dependencies -DoutputDirectory=$targetDir/lib -DincludeScope=compile
mvn install -Dmaven.test.skip=true
cp -a target/*.jar $targetDir/lib
cp -a target/props/* $targetDir/
cp -a hive2mysql mysql2hive exec $targetDir/
#cd target
#tar czf kernel-lppz-hive.tar.gz kernel-lppz-hive