#!/bin/bash
if [ $# -lt 1 ] ; then
echo "need params"
exit 
elif [ $# = 1 ] ; then
java -server -Xms1G -Xmx2G -XX:MaxNewSize=512M -Xss256k -XX:PermSize=64m -XX:MaxPermSize=128m -XX:+UseParallelGC -DLOG_HOME=logbiz -Djava.ext.dirs=$1/lib com.lppz.hive.MysqlToHdfs  
elif [ $# = 2 ] ; then
java -server -Xms1G -Xmx2G -XX:MaxNewSize=512M -Xss256k -XX:PermSize=64m -XX:MaxPermSize=128m -XX:+UseParallelGC -DLOG_HOME=logbiz -Djava.ext.dirs=$1/lib com.lppz.hive.MysqlToHdfs $2 
elif [ $# = 3 ] ; then
java -server -Xms1G -Xmx2G -XX:MaxNewSize=512M -Xss256k -XX:PermSize=64m -XX:MaxPermSize=128m -XX:+UseParallelGC -DLOG_HOME=logbiz -Djava.ext.dirs=$1/lib com.lppz.hive.MysqlToHdfs $2 "$3"
else
java -server -Xms1G -Xmx2G -XX:MaxNewSize=512M -Xss256k -XX:PermSize=64m -XX:MaxPermSize=128m -XX:+UseParallelGC -DLOG_HOME=logbiz -Djava.ext.dirs=$1/lib com.lppz.hive.MysqlToHdfs $2 "$3" "$4"
fi 
