package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class DeliveryOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.orderId
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.send
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String send;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.receive
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String receive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.outSys
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String outsys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String resultflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.receiveTime
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private Date receivetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.seq
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.result
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.orderId
     *
     * @return the value of deliveryorder.orderId
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.orderId
     *
     * @param orderid the value for deliveryorder.orderId
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.send
     *
     * @return the value of deliveryorder.send
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getSend() {
        return send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.send
     *
     * @param send the value for deliveryorder.send
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setSend(String send) {
        this.send = send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.receive
     *
     * @return the value of deliveryorder.receive
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getReceive() {
        return receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.receive
     *
     * @param receive the value for deliveryorder.receive
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setReceive(String receive) {
        this.receive = receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.outSys
     *
     * @return the value of deliveryorder.outSys
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getOutsys() {
        return outsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.outSys
     *
     * @param outsys the value for deliveryorder.outSys
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setOutsys(String outsys) {
        this.outsys = outsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.resultFlag
     *
     * @return the value of deliveryorder.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getResultflag() {
        return resultflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.resultFlag
     *
     * @param resultflag the value for deliveryorder.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setResultflag(String resultflag) {
        this.resultflag = resultflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.receiveTime
     *
     * @return the value of deliveryorder.receiveTime
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public Date getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.receiveTime
     *
     * @param receivetime the value for deliveryorder.receiveTime
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.seq
     *
     * @return the value of deliveryorder.seq
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.seq
     *
     * @param seq the value for deliveryorder.seq
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.result
     *
     * @return the value of deliveryorder.result
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.result
     *
     * @param result the value for deliveryorder.result
     *
     * @mbggenerated Fri Jul 08 11:30:13 CST 2016
     */
    public void setResult(String result) {
        this.result = result;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeliveryOrder [orderid=");
		builder.append(orderid);
		builder.append(", send=");
		builder.append(send);
		builder.append(", receive=");
		builder.append(receive);
		builder.append(", outsys=");
		builder.append(outsys);
		builder.append(", resultflag=");
		builder.append(resultflag);
		builder.append(", receivetime=");
		builder.append(receivetime);
		builder.append(", seq=");
		builder.append(seq);
		builder.append(", result=");
		builder.append(result);
		builder.append("]");
		return builder.toString();
	}
}