package com.lppz.dubbo.log.pojo;

public class ExceptionParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception_param.id
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception_param.property
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception_param.value
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception_param.exception
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    private Integer exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_param.id
     *
     * @return the value of exception_param.id
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_param.id
     *
     * @param id the value for exception_param.id
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_param.property
     *
     * @return the value of exception_param.property
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_param.property
     *
     * @param property the value for exception_param.property
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_param.value
     *
     * @return the value of exception_param.value
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_param.value
     *
     * @param value the value for exception_param.value
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_param.exception
     *
     * @return the value of exception_param.exception
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public Integer getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_param.exception
     *
     * @param exception the value for exception_param.exception
     *
     * @mbggenerated Fri Jul 08 11:32:00 CST 2016
     */
    public void setException(Integer exception) {
        this.exception = exception;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ExceptionParam [id=");
		builder.append(id);
		builder.append(", property=");
		builder.append(property);
		builder.append(", value=");
		builder.append(value);
		builder.append(", exception=");
		builder.append(exception);
		builder.append("]");
		return builder.toString();
	}
}