package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class ExceptionIdSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excpetion_id_sequence.excpetionId
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    private Integer excpetionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excpetion_id_sequence.createtime
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excpetion_id_sequence.excpetionId
     *
     * @return the value of excpetion_id_sequence.excpetionId
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    public Integer getExcpetionid() {
        return excpetionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excpetion_id_sequence.excpetionId
     *
     * @param excpetionid the value for excpetion_id_sequence.excpetionId
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    public void setExcpetionid(Integer excpetionid) {
        this.excpetionid = excpetionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excpetion_id_sequence.createtime
     *
     * @return the value of excpetion_id_sequence.createtime
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excpetion_id_sequence.createtime
     *
     * @param createtime the value for excpetion_id_sequence.createtime
     *
     * @mbggenerated Fri Jul 08 11:35:31 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ExceptionIdSequence [excpetionid=");
		builder.append(excpetionid);
		builder.append(", createtime=");
		builder.append(createtime);
		builder.append("]");
		return builder.toString();
	}
    
}