package com.lppz.dubbo.log.pojo;

public class InterfaceLogDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelogdetail.interfaceLogDetailId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    private String interfacelogdetailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelogdetail.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    private String interfacelogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelogdetail.lineNo
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    private String lineno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelogdetail.errorKey
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    private String errorkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelogdetail.message
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelogdetail.interfaceLogDetailId
     *
     * @return the value of interfacelogdetail.interfaceLogDetailId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public String getInterfacelogdetailid() {
        return interfacelogdetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelogdetail.interfaceLogDetailId
     *
     * @param interfacelogdetailid the value for interfacelogdetail.interfaceLogDetailId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public void setInterfacelogdetailid(String interfacelogdetailid) {
        this.interfacelogdetailid = interfacelogdetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelogdetail.interfaceLogId
     *
     * @return the value of interfacelogdetail.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public String getInterfacelogid() {
        return interfacelogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelogdetail.interfaceLogId
     *
     * @param interfacelogid the value for interfacelogdetail.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public void setInterfacelogid(String interfacelogid) {
        this.interfacelogid = interfacelogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelogdetail.lineNo
     *
     * @return the value of interfacelogdetail.lineNo
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public String getLineno() {
        return lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelogdetail.lineNo
     *
     * @param lineno the value for interfacelogdetail.lineNo
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public void setLineno(String lineno) {
        this.lineno = lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelogdetail.errorKey
     *
     * @return the value of interfacelogdetail.errorKey
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public String getErrorkey() {
        return errorkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelogdetail.errorKey
     *
     * @param errorkey the value for interfacelogdetail.errorKey
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public void setErrorkey(String errorkey) {
        this.errorkey = errorkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelogdetail.message
     *
     * @return the value of interfacelogdetail.message
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelogdetail.message
     *
     * @param message the value for interfacelogdetail.message
     *
     * @mbggenerated Fri Jul 08 11:36:12 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("InterfaceLogDetail [interfacelogdetailid=");
		builder.append(interfacelogdetailid);
		builder.append(", interfacelogid=");
		builder.append(interfacelogid);
		builder.append(", lineno=");
		builder.append(lineno);
		builder.append(", errorkey=");
		builder.append(errorkey);
		builder.append(", message=");
		builder.append(message);
		builder.append("]");
		return builder.toString();
	}
}