package com.lppz.dubbo.log.pojo;

import java.util.Date;
import java.util.List;

public class InterfaceLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String interfacelogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.sourceType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String sourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.targetType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String targettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.interfaceId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String interfaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.interfaceName
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String interfacename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String resultflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.startDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.endDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.piFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String piflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacelog.in_messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    private String inMessageid;
    
    private List<InterfaceLogDetail> detailList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.interfaceLogId
     *
     * @return the value of interfacelog.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getInterfacelogid() {
        return interfacelogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.interfaceLogId
     *
     * @param interfacelogid the value for interfacelog.interfaceLogId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setInterfacelogid(String interfacelogid) {
        this.interfacelogid = interfacelogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.sourceType
     *
     * @return the value of interfacelog.sourceType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.sourceType
     *
     * @param sourcetype the value for interfacelog.sourceType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setSourcetype(String sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.targetType
     *
     * @return the value of interfacelog.targetType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getTargettype() {
        return targettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.targetType
     *
     * @param targettype the value for interfacelog.targetType
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setTargettype(String targettype) {
        this.targettype = targettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.messageId
     *
     * @return the value of interfacelog.messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.messageId
     *
     * @param messageid the value for interfacelog.messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.interfaceId
     *
     * @return the value of interfacelog.interfaceId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getInterfaceid() {
        return interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.interfaceId
     *
     * @param interfaceid the value for interfacelog.interfaceId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setInterfaceid(String interfaceid) {
        this.interfaceid = interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.interfaceName
     *
     * @return the value of interfacelog.interfaceName
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getInterfacename() {
        return interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.interfaceName
     *
     * @param interfacename the value for interfacelog.interfaceName
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.resultFlag
     *
     * @return the value of interfacelog.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getResultflag() {
        return resultflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.resultFlag
     *
     * @param resultflag the value for interfacelog.resultFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setResultflag(String resultflag) {
        this.resultflag = resultflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.startDate
     *
     * @return the value of interfacelog.startDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.startDate
     *
     * @param startdate the value for interfacelog.startDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.endDate
     *
     * @return the value of interfacelog.endDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.endDate
     *
     * @param enddate the value for interfacelog.endDate
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.piFlag
     *
     * @return the value of interfacelog.piFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getPiflag() {
        return piflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.piFlag
     *
     * @param piflag the value for interfacelog.piFlag
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setPiflag(String piflag) {
        this.piflag = piflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacelog.in_messageId
     *
     * @return the value of interfacelog.in_messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public String getInMessageid() {
        return inMessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacelog.in_messageId
     *
     * @param inMessageid the value for interfacelog.in_messageId
     *
     * @mbggenerated Fri Jul 08 11:35:54 CST 2016
     */
    public void setInMessageid(String inMessageid) {
        this.inMessageid = inMessageid;
    }

	public List<InterfaceLogDetail> getDetailList() {
		return detailList;
	}

	public void setDetailList(List<InterfaceLogDetail> detailList) {
		this.detailList = detailList;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("InterfaceLog [interfacelogid=");
		builder.append(interfacelogid);
		builder.append(", sourcetype=");
		builder.append(sourcetype);
		builder.append(", targettype=");
		builder.append(targettype);
		builder.append(", messageid=");
		builder.append(messageid);
		builder.append(", interfaceid=");
		builder.append(interfaceid);
		builder.append(", interfacename=");
		builder.append(interfacename);
		builder.append(", resultflag=");
		builder.append(resultflag);
		builder.append(", startdate=");
		builder.append(startdate);
		builder.append(", enddate=");
		builder.append(enddate);
		builder.append(", piflag=");
		builder.append(piflag);
		builder.append(", inMessageid=");
		builder.append(inMessageid);
		builder.append(", detailList=");
		builder.append(detailList);
		builder.append("]");
		return builder.toString();
	}
}