package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class LackOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.mergeorderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String mergeorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.orderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.seq
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.orderlineid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String orderlineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.werehousecode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String werehousecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.productcode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.productname
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.receivetime
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private Date receivetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.mergeflag
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String mergeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.issuccess
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String issuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lackorder.message
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.mergeorderid
     *
     * @return the value of lackorder.mergeorderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getMergeorderid() {
        return mergeorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.mergeorderid
     *
     * @param mergeorderid the value for lackorder.mergeorderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setMergeorderid(String mergeorderid) {
        this.mergeorderid = mergeorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.orderid
     *
     * @return the value of lackorder.orderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.orderid
     *
     * @param orderid the value for lackorder.orderid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.seq
     *
     * @return the value of lackorder.seq
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.seq
     *
     * @param seq the value for lackorder.seq
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.orderlineid
     *
     * @return the value of lackorder.orderlineid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getOrderlineid() {
        return orderlineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.orderlineid
     *
     * @param orderlineid the value for lackorder.orderlineid
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setOrderlineid(String orderlineid) {
        this.orderlineid = orderlineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.werehousecode
     *
     * @return the value of lackorder.werehousecode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getWerehousecode() {
        return werehousecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.werehousecode
     *
     * @param werehousecode the value for lackorder.werehousecode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setWerehousecode(String werehousecode) {
        this.werehousecode = werehousecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.productcode
     *
     * @return the value of lackorder.productcode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.productcode
     *
     * @param productcode the value for lackorder.productcode
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.productname
     *
     * @return the value of lackorder.productname
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.productname
     *
     * @param productname the value for lackorder.productname
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.receivetime
     *
     * @return the value of lackorder.receivetime
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public Date getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.receivetime
     *
     * @param receivetime the value for lackorder.receivetime
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.mergeflag
     *
     * @return the value of lackorder.mergeflag
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getMergeflag() {
        return mergeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.mergeflag
     *
     * @param mergeflag the value for lackorder.mergeflag
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setMergeflag(String mergeflag) {
        this.mergeflag = mergeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.issuccess
     *
     * @return the value of lackorder.issuccess
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.issuccess
     *
     * @param issuccess the value for lackorder.issuccess
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setIssuccess(String issuccess) {
        this.issuccess = issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lackorder.message
     *
     * @return the value of lackorder.message
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lackorder.message
     *
     * @param message the value for lackorder.message
     *
     * @mbggenerated Fri Jul 08 11:36:30 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("LackOrder [mergeorderid=");
		builder.append(mergeorderid);
		builder.append(", orderid=");
		builder.append(orderid);
		builder.append(", seq=");
		builder.append(seq);
		builder.append(", orderlineid=");
		builder.append(orderlineid);
		builder.append(", werehousecode=");
		builder.append(werehousecode);
		builder.append(", productcode=");
		builder.append(productcode);
		builder.append(", productname=");
		builder.append(productname);
		builder.append(", receivetime=");
		builder.append(receivetime);
		builder.append(", mergeflag=");
		builder.append(mergeflag);
		builder.append(", issuccess=");
		builder.append(issuccess);
		builder.append(", message=");
		builder.append(message);
		builder.append("]");
		return builder.toString();
	}
}