package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class OptRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.funcname
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String funcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.optType
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String opttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.userId
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.userName
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.ipAddr
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.optTime
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private Date opttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.beforMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String beformsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.afterMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String aftermsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optrecord.remark
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.funcname
     *
     * @return the value of optrecord.funcname
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getFuncname() {
        return funcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.funcname
     *
     * @param funcname the value for optrecord.funcname
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setFuncname(String funcname) {
        this.funcname = funcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.optType
     *
     * @return the value of optrecord.optType
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getOpttype() {
        return opttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.optType
     *
     * @param opttype the value for optrecord.optType
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setOpttype(String opttype) {
        this.opttype = opttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.userId
     *
     * @return the value of optrecord.userId
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.userId
     *
     * @param userid the value for optrecord.userId
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.userName
     *
     * @return the value of optrecord.userName
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.userName
     *
     * @param username the value for optrecord.userName
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.ipAddr
     *
     * @return the value of optrecord.ipAddr
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.ipAddr
     *
     * @param ipaddr the value for optrecord.ipAddr
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.optTime
     *
     * @return the value of optrecord.optTime
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public Date getOpttime() {
        return opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.optTime
     *
     * @param opttime the value for optrecord.optTime
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setOpttime(Date opttime) {
        this.opttime = opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.beforMsg
     *
     * @return the value of optrecord.beforMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getBeformsg() {
        return beformsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.beforMsg
     *
     * @param beformsg the value for optrecord.beforMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setBeformsg(String beformsg) {
        this.beformsg = beformsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.afterMsg
     *
     * @return the value of optrecord.afterMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getAftermsg() {
        return aftermsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.afterMsg
     *
     * @param aftermsg the value for optrecord.afterMsg
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setAftermsg(String aftermsg) {
        this.aftermsg = aftermsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optrecord.remark
     *
     * @return the value of optrecord.remark
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optrecord.remark
     *
     * @param remark the value for optrecord.remark
     *
     * @mbggenerated Fri Jul 08 11:36:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("OptRecord [funcname=");
		builder.append(funcname);
		builder.append(", opttype=");
		builder.append(opttype);
		builder.append(", userid=");
		builder.append(userid);
		builder.append(", username=");
		builder.append(username);
		builder.append(", ipaddr=");
		builder.append(ipaddr);
		builder.append(", opttime=");
		builder.append(opttime);
		builder.append(", beformsg=");
		builder.append(beformsg);
		builder.append(", aftermsg=");
		builder.append(aftermsg);
		builder.append(", remark=");
		builder.append(remark);
		builder.append("]");
		return builder.toString();
	}
    
}