package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class OrderLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.uuid
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.appName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.className
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.methodName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String methodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.productId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.productName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.changeMoney
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String changemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.operate
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.remark
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.operateUser
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String operateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.operateTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.status
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.outOrderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String outorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.orderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.systemSourcing
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String systemsourcing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.sourcingLocation
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String sourcinglocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.sourcingResult
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String sourcingresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.endTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.returnCode
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String returncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.result
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlog.userId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.uuid
     *
     * @return the value of orderlog.uuid
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.uuid
     *
     * @param uuid the value for orderlog.uuid
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.appName
     *
     * @return the value of orderlog.appName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.appName
     *
     * @param appname the value for orderlog.appName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.className
     *
     * @return the value of orderlog.className
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.className
     *
     * @param classname the value for orderlog.className
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.methodName
     *
     * @return the value of orderlog.methodName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.methodName
     *
     * @param methodname the value for orderlog.methodName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.productId
     *
     * @return the value of orderlog.productId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.productId
     *
     * @param productid the value for orderlog.productId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.productName
     *
     * @return the value of orderlog.productName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.productName
     *
     * @param productname the value for orderlog.productName
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.changeMoney
     *
     * @return the value of orderlog.changeMoney
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getChangemoney() {
        return changemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.changeMoney
     *
     * @param changemoney the value for orderlog.changeMoney
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setChangemoney(String changemoney) {
        this.changemoney = changemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.operate
     *
     * @return the value of orderlog.operate
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.operate
     *
     * @param operate the value for orderlog.operate
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setOperate(String operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.remark
     *
     * @return the value of orderlog.remark
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.remark
     *
     * @param remark the value for orderlog.remark
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.operateUser
     *
     * @return the value of orderlog.operateUser
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getOperateuser() {
        return operateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.operateUser
     *
     * @param operateuser the value for orderlog.operateUser
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setOperateuser(String operateuser) {
        this.operateuser = operateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.operateTime
     *
     * @return the value of orderlog.operateTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.operateTime
     *
     * @param operatetime the value for orderlog.operateTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.status
     *
     * @return the value of orderlog.status
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.status
     *
     * @param status the value for orderlog.status
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.outOrderId
     *
     * @return the value of orderlog.outOrderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getOutorderid() {
        return outorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.outOrderId
     *
     * @param outorderid the value for orderlog.outOrderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setOutorderid(String outorderid) {
        this.outorderid = outorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.orderId
     *
     * @return the value of orderlog.orderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.orderId
     *
     * @param orderid the value for orderlog.orderId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.systemSourcing
     *
     * @return the value of orderlog.systemSourcing
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getSystemsourcing() {
        return systemsourcing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.systemSourcing
     *
     * @param systemsourcing the value for orderlog.systemSourcing
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setSystemsourcing(String systemsourcing) {
        this.systemsourcing = systemsourcing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.sourcingLocation
     *
     * @return the value of orderlog.sourcingLocation
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getSourcinglocation() {
        return sourcinglocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.sourcingLocation
     *
     * @param sourcinglocation the value for orderlog.sourcingLocation
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setSourcinglocation(String sourcinglocation) {
        this.sourcinglocation = sourcinglocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.sourcingResult
     *
     * @return the value of orderlog.sourcingResult
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getSourcingresult() {
        return sourcingresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.sourcingResult
     *
     * @param sourcingresult the value for orderlog.sourcingResult
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setSourcingresult(String sourcingresult) {
        this.sourcingresult = sourcingresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.endTime
     *
     * @return the value of orderlog.endTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.endTime
     *
     * @param endtime the value for orderlog.endTime
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.returnCode
     *
     * @return the value of orderlog.returnCode
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getReturncode() {
        return returncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.returnCode
     *
     * @param returncode the value for orderlog.returnCode
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setReturncode(String returncode) {
        this.returncode = returncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.result
     *
     * @return the value of orderlog.result
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.result
     *
     * @param result the value for orderlog.result
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlog.userId
     *
     * @return the value of orderlog.userId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlog.userId
     *
     * @param userid the value for orderlog.userId
     *
     * @mbggenerated Fri Jul 08 15:58:47 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("OrderLog [uuid=");
		builder.append(uuid);
		builder.append(", appname=");
		builder.append(appname);
		builder.append(", classname=");
		builder.append(classname);
		builder.append(", methodname=");
		builder.append(methodname);
		builder.append(", productid=");
		builder.append(productid);
		builder.append(", productname=");
		builder.append(productname);
		builder.append(", changemoney=");
		builder.append(changemoney);
		builder.append(", operate=");
		builder.append(operate);
		builder.append(", remark=");
		builder.append(remark);
		builder.append(", operateuser=");
		builder.append(operateuser);
		builder.append(", operatetime=");
		builder.append(operatetime);
		builder.append(", status=");
		builder.append(status);
		builder.append(", outorderid=");
		builder.append(outorderid);
		builder.append(", orderid=");
		builder.append(orderid);
		builder.append(", systemsourcing=");
		builder.append(systemsourcing);
		builder.append(", sourcinglocation=");
		builder.append(sourcinglocation);
		builder.append(", sourcingresult=");
		builder.append(sourcingresult);
		builder.append(", endtime=");
		builder.append(endtime);
		builder.append(", returncode=");
		builder.append(returncode);
		builder.append(", result=");
		builder.append(result);
		builder.append(", userid=");
		builder.append(userid);
		builder.append("]");
		return builder.toString();
	}
    
}