package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class ProductSyn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.productName
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.productCode
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.productPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String productprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.lowesPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String lowesprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private Date syndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String extend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.extend4
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String extend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productsyn.extend5
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    private String extend5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.productId
     *
     * @return the value of productsyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.productId
     *
     * @param productid the value for productsyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.productName
     *
     * @return the value of productsyn.productName
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.productName
     *
     * @param productname the value for productsyn.productName
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.productCode
     *
     * @return the value of productsyn.productCode
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.productCode
     *
     * @param productcode the value for productsyn.productCode
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.productPrice
     *
     * @return the value of productsyn.productPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.productPrice
     *
     * @param productprice the value for productsyn.productPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setProductprice(String productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.lowesPrice
     *
     * @return the value of productsyn.lowesPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getLowesprice() {
        return lowesprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.lowesPrice
     *
     * @param lowesprice the value for productsyn.lowesPrice
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setLowesprice(String lowesprice) {
        this.lowesprice = lowesprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.synDate
     *
     * @return the value of productsyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public Date getSyndate() {
        return syndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.synDate
     *
     * @param syndate the value for productsyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setSyndate(Date syndate) {
        this.syndate = syndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.extend1
     *
     * @return the value of productsyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.extend1
     *
     * @param extend1 the value for productsyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.extend2
     *
     * @return the value of productsyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.extend2
     *
     * @param extend2 the value for productsyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.extend3
     *
     * @return the value of productsyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.extend3
     *
     * @param extend3 the value for productsyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.extend4
     *
     * @return the value of productsyn.extend4
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.extend4
     *
     * @param extend4 the value for productsyn.extend4
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productsyn.extend5
     *
     * @return the value of productsyn.extend5
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public String getExtend5() {
        return extend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productsyn.extend5
     *
     * @param extend5 the value for productsyn.extend5
     *
     * @mbggenerated Fri Jul 08 11:37:28 CST 2016
     */
    public void setExtend5(String extend5) {
        this.extend5 = extend5;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ProductSyn [productid=");
		builder.append(productid);
		builder.append(", productname=");
		builder.append(productname);
		builder.append(", productcode=");
		builder.append(productcode);
		builder.append(", productprice=");
		builder.append(productprice);
		builder.append(", lowesprice=");
		builder.append(lowesprice);
		builder.append(", syndate=");
		builder.append(syndate);
		builder.append(", extend1=");
		builder.append(extend1);
		builder.append(", extend2=");
		builder.append(extend2);
		builder.append(", extend3=");
		builder.append(extend3);
		builder.append(", extend4=");
		builder.append(extend4);
		builder.append(", extend5=");
		builder.append(extend5);
		builder.append("]");
		return builder.toString();
	}
    
}