package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class StockSyn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.whouse
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String whouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.stockType
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String stocktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.inOutFlag
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String inoutflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.synWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String synway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.incrementSynWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String incrementsynway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.synQuantity
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private Integer synquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private Date syndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocksyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    private String extend3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.productId
     *
     * @return the value of stocksyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.productId
     *
     * @param productid the value for stocksyn.productId
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.whouse
     *
     * @return the value of stocksyn.whouse
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getWhouse() {
        return whouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.whouse
     *
     * @param whouse the value for stocksyn.whouse
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setWhouse(String whouse) {
        this.whouse = whouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.stockType
     *
     * @return the value of stocksyn.stockType
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getStocktype() {
        return stocktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.stockType
     *
     * @param stocktype the value for stocksyn.stockType
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setStocktype(String stocktype) {
        this.stocktype = stocktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.inOutFlag
     *
     * @return the value of stocksyn.inOutFlag
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getInoutflag() {
        return inoutflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.inOutFlag
     *
     * @param inoutflag the value for stocksyn.inOutFlag
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setInoutflag(String inoutflag) {
        this.inoutflag = inoutflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.synWay
     *
     * @return the value of stocksyn.synWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getSynway() {
        return synway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.synWay
     *
     * @param synway the value for stocksyn.synWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setSynway(String synway) {
        this.synway = synway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.incrementSynWay
     *
     * @return the value of stocksyn.incrementSynWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getIncrementsynway() {
        return incrementsynway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.incrementSynWay
     *
     * @param incrementsynway the value for stocksyn.incrementSynWay
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setIncrementsynway(String incrementsynway) {
        this.incrementsynway = incrementsynway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.synQuantity
     *
     * @return the value of stocksyn.synQuantity
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public Integer getSynquantity() {
        return synquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.synQuantity
     *
     * @param synquantity the value for stocksyn.synQuantity
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setSynquantity(Integer synquantity) {
        this.synquantity = synquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.synDate
     *
     * @return the value of stocksyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public Date getSyndate() {
        return syndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.synDate
     *
     * @param syndate the value for stocksyn.synDate
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setSyndate(Date syndate) {
        this.syndate = syndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.extend1
     *
     * @return the value of stocksyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.extend1
     *
     * @param extend1 the value for stocksyn.extend1
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.extend2
     *
     * @return the value of stocksyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.extend2
     *
     * @param extend2 the value for stocksyn.extend2
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocksyn.extend3
     *
     * @return the value of stocksyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocksyn.extend3
     *
     * @param extend3 the value for stocksyn.extend3
     *
     * @mbggenerated Fri Jul 08 11:37:42 CST 2016
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("StockSyn [productid=");
		builder.append(productid);
		builder.append(", whouse=");
		builder.append(whouse);
		builder.append(", stocktype=");
		builder.append(stocktype);
		builder.append(", inoutflag=");
		builder.append(inoutflag);
		builder.append(", synway=");
		builder.append(synway);
		builder.append(", incrementsynway=");
		builder.append(incrementsynway);
		builder.append(", synquantity=");
		builder.append(synquantity);
		builder.append(", syndate=");
		builder.append(syndate);
		builder.append(", extend1=");
		builder.append(extend1);
		builder.append(", extend2=");
		builder.append(extend2);
		builder.append(", extend3=");
		builder.append(extend3);
		builder.append("]");
		return builder.toString();
	}
}