package com.lppz.dubbo.log.pojo;

import java.util.Date;

public class Tlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.uuid
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.appId
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.appName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.className
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.methodName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String methodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.costTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private Long costtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.remoteIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String remoteip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.localIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String localip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.exceptionFlag
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private Byte exceptionflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.refCode
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String refcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.resultInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String resultinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.exceptionInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String exceptioninfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logHeader
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String logheader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.createTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.consumerTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private Date consumertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logType
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.paramInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    private String paraminfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.uuid
     *
     * @return the value of t_log.uuid
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.uuid
     *
     * @param uuid the value for t_log.uuid
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.appId
     *
     * @return the value of t_log.appId
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.appId
     *
     * @param appid the value for t_log.appId
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.appName
     *
     * @return the value of t_log.appName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.appName
     *
     * @param appname the value for t_log.appName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.className
     *
     * @return the value of t_log.className
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.className
     *
     * @param classname the value for t_log.className
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.methodName
     *
     * @return the value of t_log.methodName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.methodName
     *
     * @param methodname the value for t_log.methodName
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.costTime
     *
     * @return the value of t_log.costTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public Long getCosttime() {
        return costtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.costTime
     *
     * @param costtime the value for t_log.costTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setCosttime(Long costtime) {
        this.costtime = costtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.remoteIp
     *
     * @return the value of t_log.remoteIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getRemoteip() {
        return remoteip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.remoteIp
     *
     * @param remoteip the value for t_log.remoteIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setRemoteip(String remoteip) {
        this.remoteip = remoteip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.localIp
     *
     * @return the value of t_log.localIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getLocalip() {
        return localip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.localIp
     *
     * @param localip the value for t_log.localIp
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setLocalip(String localip) {
        this.localip = localip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.exceptionFlag
     *
     * @return the value of t_log.exceptionFlag
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public Byte getExceptionflag() {
        return exceptionflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.exceptionFlag
     *
     * @param exceptionflag the value for t_log.exceptionFlag
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setExceptionflag(Byte exceptionflag) {
        this.exceptionflag = exceptionflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.refCode
     *
     * @return the value of t_log.refCode
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getRefcode() {
        return refcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.refCode
     *
     * @param refcode the value for t_log.refCode
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setRefcode(String refcode) {
        this.refcode = refcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.resultInfo
     *
     * @return the value of t_log.resultInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getResultinfo() {
        return resultinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.resultInfo
     *
     * @param resultinfo the value for t_log.resultInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setResultinfo(String resultinfo) {
        this.resultinfo = resultinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.exceptionInfo
     *
     * @return the value of t_log.exceptionInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getExceptioninfo() {
        return exceptioninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.exceptionInfo
     *
     * @param exceptioninfo the value for t_log.exceptionInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setExceptioninfo(String exceptioninfo) {
        this.exceptioninfo = exceptioninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logHeader
     *
     * @return the value of t_log.logHeader
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getLogheader() {
        return logheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logHeader
     *
     * @param logheader the value for t_log.logHeader
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setLogheader(String logheader) {
        this.logheader = logheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.createTime
     *
     * @return the value of t_log.createTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.createTime
     *
     * @param createtime the value for t_log.createTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.consumerTime
     *
     * @return the value of t_log.consumerTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public Date getConsumertime() {
        return consumertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.consumerTime
     *
     * @param consumertime the value for t_log.consumerTime
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setConsumertime(Date consumertime) {
        this.consumertime = consumertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logType
     *
     * @return the value of t_log.logType
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logType
     *
     * @param logtype the value for t_log.logType
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.paramInfo
     *
     * @return the value of t_log.paramInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public String getParaminfo() {
        return paraminfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.paramInfo
     *
     * @param paraminfo the value for t_log.paramInfo
     *
     * @mbggenerated Fri Jul 08 11:38:00 CST 2016
     */
    public void setParaminfo(String paraminfo) {
        this.paraminfo = paraminfo;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Tlog [uuid=");
		builder.append(uuid);
		builder.append(", appid=");
		builder.append(appid);
		builder.append(", appname=");
		builder.append(appname);
		builder.append(", classname=");
		builder.append(classname);
		builder.append(", methodname=");
		builder.append(methodname);
		builder.append(", costtime=");
		builder.append(costtime);
		builder.append(", remoteip=");
		builder.append(remoteip);
		builder.append(", localip=");
		builder.append(localip);
		builder.append(", exceptionflag=");
		builder.append(exceptionflag);
		builder.append(", refcode=");
		builder.append(refcode);
		builder.append(", resultinfo=");
		builder.append(resultinfo);
		builder.append(", exceptioninfo=");
		builder.append(exceptioninfo);
		builder.append(", logheader=");
		builder.append(logheader);
		builder.append(", createtime=");
		builder.append(createtime);
		builder.append(", consumertime=");
		builder.append(consumertime);
		builder.append(", logtype=");
		builder.append(logtype);
		builder.append(", paraminfo=");
		builder.append(paraminfo);
		builder.append("]");
		return builder.toString();
	}
    
}