#!/bin/bash
targetDir="target/kernel-lppz-dal"
mvn clean dependency:copy-dependencies -DoutputDirectory=$targetDir/lib -DincludeScope=compile
mvn install -Dmaven.test.skip=true
cp -a target/*.jar lib/* $targetDir/lib
mkdir -p $targetDir/conf
mkdir -p $targetDir/logs
cp -a target/props/* conf/* $targetDir/conf
cp -a init_zk_data startup $targetDir/
